package Booking;

import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.ImageIcon;
import java.awt.Color;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * M_Time.java
 *
 * Created on Jul 10, 2017, 11:29:37 AM
 */

/**
 *
 * @author lab-2-user-4
 */
public class M_Time extends javax.swing.JFrame {

    /** Creates new form M_Time */
    public M_Time() {
        initComponents();
        jPanel1.setBackground(Color.BLACK);

    }
public String mabout="wow";
 String a=("C:\\Users\\Prerak Jain\\Desktop\\Projects\\Prerak\\src\\Images\\");
void detail(String mname){
    int DDD=0;{
    try{
        Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abcd","root","sps");
        Statement stmt=con.createStatement();
        String query= "Select * from movie_detail where Movie_Name='"+mname+"';" ;
        ResultSet rs1=stmt.executeQuery(query);
        rs1.next();
        DDD=rs1.getInt(1);
         M_name.setText(mname);
         M_rating.setText(rs1.getString("rating"));
         M_category.setText(rs1.getString("category"));
         M_lang.setText(rs1.getString("language"));
         M_hrs.setText(rs1.getString("Running_Time"));
         M_DP.setText(rs1.getString("Director"));
         M_DP1.setText(rs1.getString("cast_1"));
         M_DP2.setText(rs1.getString("cast_2"));
         M_DP3.setText(rs1.getString("cast_3"));
         rs1.close();
    }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
         try{
        Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abcd","root","sps");
        Statement stmt=con.createStatement();
        String query= "Select * from hall_detail where Movie_No="+DDD+";" ;
        System.out.print(DDD+"");
        ResultSet rs=stmt.executeQuery(query);
        rs.next();
            M_hall1.setText(rs.getString(1));
            M_t1.setText(rs.getString(4));
            M_t2.setText(rs.getString(5));
            M_t3.setText(rs.getString(6));
        rs.next();
            M_hall2.setText(rs.getString(1));
            M_t4.setText(rs.getString(4));
            M_t5.setText(rs.getString(5));
            M_t6.setText(rs.getString(6));
            rs.next();
            M_hall3.setText(rs.getString(1));
            M_t7.setText(rs.getString(4));
            M_t8.setText(rs.getString(5));
            M_t9.setText(rs.getString(6));

}

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
}
}

    

    void movie(String name, double votes, String rating, String category,
               String M_D, String M_C1, String M_C2, String M_C3, String M_language,
               String M_Hrs, String M_about, int DDD) {
         M_name.setText(name);
         M_rating.setText(""+votes);
         M_rating.setText(rating);
         M_category.setText(category);
         M_lang.setText(M_language);
         M_hrs.setText(M_Hrs);
         mabout=M_about;
          M_DP.setText(M_D);
         M_DP1.setText(M_C1);
         M_DP2.setText(M_C2);
         M_DP3.setText(M_C3);
try{
        Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abcd","root","sps");
        Statement stmt=con.createStatement();
        String query= "Select * from hall_detail where Movie_No="+DDD+";" ;
        System.out.print(DDD+"");
        ResultSet rs=stmt.executeQuery(query);
        rs.next();
            M_hall1.setText(rs.getString(1));
            M_t1.setText(rs.getString(4));
            M_t2.setText(rs.getString(5));
            M_t3.setText(rs.getString(6));
        rs.next();
            M_hall2.setText(rs.getString(1));
            M_t4.setText(rs.getString(4));
            M_t5.setText(rs.getString(5));
            M_t6.setText(rs.getString(6));
            rs.next();
            M_hall3.setText(rs.getString(1));
            M_t7.setText(rs.getString(4));
            M_t8.setText(rs.getString(5));
            M_t9.setText(rs.getString(6));

}
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
         

    }

    void name(String mname) {
        detail(mname);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl1 = new javax.swing.JDialog();
        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        namehall = new javax.swing.JLabel();
        About1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        About = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        M_t1 = new javax.swing.JButton();
        M_t2 = new javax.swing.JButton();
        M_t3 = new javax.swing.JButton();
        M_t4 = new javax.swing.JButton();
        M_t5 = new javax.swing.JButton();
        M_t6 = new javax.swing.JButton();
        M_t7 = new javax.swing.JButton();
        M_t8 = new javax.swing.JButton();
        M_t9 = new javax.swing.JButton();
        M_hall1 = new javax.swing.JLabel();
        M_hall1Info = new javax.swing.JLabel();
        M_hall2 = new javax.swing.JLabel();
        M_hall2Info = new javax.swing.JLabel();
        M_hall3 = new javax.swing.JLabel();
        M_hall3Info = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        M_DP3 = new javax.swing.JLabel();
        M_rating = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        M_lang = new javax.swing.JLabel();
        M_category = new javax.swing.JLabel();
        M_votes1 = new javax.swing.JLabel();
        M_hrs = new javax.swing.JLabel();
        M_DP = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        M_DP1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        M_name = new javax.swing.JLabel();
        M_MovieInfo = new javax.swing.JLabel();
        M_DP2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jl1.setMinimumSize(new java.awt.Dimension(350, 350));

        L1.setText("Hall Name :");

        L2.setText("Ratings");

        About1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        About1.setText("*****");

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 255)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        About.setBackground(new java.awt.Color(50, 2, 2));
        About.setColumns(20);
        About.setForeground(new java.awt.Color(0, 255, 255));
        About.setLineWrap(true);
        About.setRows(5);
        About.setWrapStyleWord(true);
        About.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 204)));
        jScrollPane1.setViewportView(About);

        javax.swing.GroupLayout jl1Layout = new javax.swing.GroupLayout(jl1.getContentPane());
        jl1.getContentPane().setLayout(jl1Layout);
        jl1Layout.setHorizontalGroup(
            jl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jl1Layout.createSequentialGroup()
                .addGroup(jl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jl1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jl1Layout.createSequentialGroup()
                                .addComponent(L2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(244, 244, 244)
                                .addComponent(About1))
                            .addGroup(jl1Layout.createSequentialGroup()
                                .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(namehall, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jl1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jButton1))
                    .addGroup(jl1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        jl1Layout.setVerticalGroup(
            jl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jl1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namehall, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(About1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TicPic - Time \nSelection");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(850, 630));
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 212, 792, 10);

        M_t1.setText("12:00");
        M_t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_t1ActionPerformed(evt);
            }
        });
        getContentPane().add(M_t1);
        M_t1.setBounds(61, 353, 70, 23);

        M_t2.setText("16:00");
        M_t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_t2ActionPerformed(evt);
            }
        });
        getContentPane().add(M_t2);
        M_t2.setBounds(335, 353, 80, 23);

        M_t3.setText("20:00");
        M_t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_t3ActionPerformed(evt);
            }
        });
        getContentPane().add(M_t3);
        M_t3.setBounds(563, 353, 90, 23);

        M_t4.setText("10:00");
        M_t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_t4ActionPerformed(evt);
            }
        });
        getContentPane().add(M_t4);
        M_t4.setBounds(61, 453, 70, 23);

        M_t5.setText("14:00");
        M_t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_t5ActionPerformed(evt);
            }
        });
        getContentPane().add(M_t5);
        M_t5.setBounds(335, 453, 80, 23);

        M_t6.setText("21:00");
        M_t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_t6ActionPerformed(evt);
            }
        });
        getContentPane().add(M_t6);
        M_t6.setBounds(563, 453, 90, 23);

        M_t7.setText("9:00");
        M_t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_t7ActionPerformed(evt);
            }
        });
        getContentPane().add(M_t7);
        M_t7.setBounds(61, 545, 70, 23);

        M_t8.setText("17:00");
        M_t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_t8ActionPerformed(evt);
            }
        });
        getContentPane().add(M_t8);
        M_t8.setBounds(335, 545, 80, 23);

        M_t9.setText("22:00");
        M_t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_t9ActionPerformed(evt);
            }
        });
        getContentPane().add(M_t9);
        M_t9.setBounds(563, 545, 90, 23);

        M_hall1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        M_hall1.setForeground(new java.awt.Color(255, 255, 255));
        M_hall1.setText("INOX : PINK SQUARE");
        getContentPane().add(M_hall1);
        M_hall1.setBounds(61, 293, 152, 17);

        M_hall1Info.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        M_hall1Info.setForeground(new java.awt.Color(255, 255, 255));
        M_hall1Info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        M_hall1Info.setText("?");
        M_hall1Info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        M_hall1Info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                M_hall1InfoMouseReleased(evt);
            }
        });
        getContentPane().add(M_hall1Info);
        M_hall1Info.setBounds(246, 292, 16, 19);

        M_hall2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        M_hall2.setForeground(new java.awt.Color(255, 255, 255));
        M_hall2.setText("CINEPOLIS : WTP");
        getContentPane().add(M_hall2);
        M_hall2.setBounds(61, 405, 126, 17);

        M_hall2Info.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        M_hall2Info.setForeground(new java.awt.Color(255, 255, 255));
        M_hall2Info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        M_hall2Info.setText("?");
        M_hall2Info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        M_hall2Info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                M_hall2InfoMouseReleased(evt);
            }
        });
        getContentPane().add(M_hall2Info);
        M_hall2Info.setBounds(246, 404, 16, 19);

        M_hall3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        M_hall3.setForeground(new java.awt.Color(255, 255, 255));
        M_hall3.setText("INOX : CRYSTAL PALM");
        getContentPane().add(M_hall3);
        M_hall3.setBounds(61, 495, 160, 17);

        M_hall3Info.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        M_hall3Info.setForeground(new java.awt.Color(255, 255, 255));
        M_hall3Info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        M_hall3Info.setText("?");
        M_hall3Info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        M_hall3Info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                M_hall3InfoMouseReleased(evt);
            }
        });
        getContentPane().add(M_hall3Info);
        M_hall3Info.setBounds(249, 494, 16, 19);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Booking/newFolder/M_TIME.jpg"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(700, 600));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 230, 812, 354);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        M_DP3.setForeground(new java.awt.Color(255, 255, 255));
        M_DP3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        M_rating.setForeground(new java.awt.Color(255, 255, 255));
        M_rating.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Language");

        M_lang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        M_lang.setForeground(new java.awt.Color(255, 255, 255));
        M_lang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        M_category.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        M_category.setForeground(new java.awt.Color(255, 255, 255));
        M_category.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        M_category.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        M_votes1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        M_votes1.setForeground(new java.awt.Color(255, 255, 255));
        M_votes1.setText("% Votes");

        M_hrs.setForeground(new java.awt.Color(255, 255, 255));
        M_hrs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        M_DP.setForeground(new java.awt.Color(255, 255, 255));
        M_DP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mins");

        M_DP1.setForeground(new java.awt.Color(255, 255, 255));
        M_DP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cast");

        M_name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        M_name.setForeground(new java.awt.Color(255, 255, 255));
        M_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        M_MovieInfo.setForeground(new java.awt.Color(255, 255, 255));
        M_MovieInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        M_MovieInfo.setText("?");
        M_MovieInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        M_MovieInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                M_MovieInfoMouseReleased(evt);
            }
        });

        M_DP2.setForeground(new java.awt.Color(255, 255, 255));
        M_DP2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Director");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(M_category, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(M_name, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(M_MovieInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(M_rating, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(M_votes1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(M_hrs, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)))
                        .addGap(153, 153, 153)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addComponent(M_lang, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(M_DP1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(M_DP2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(M_DP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(M_DP, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(M_votes1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_name, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(M_MovieInfo)
                                .addComponent(M_rating, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(M_DP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4))
                            .addComponent(M_DP3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(M_DP2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(M_category, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(M_hrs, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(M_DP1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(M_lang, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 20, 760, 180);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 890, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    jl1.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void M_MovieInfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MovieInfoMouseReleased
        jl1.setVisible(true);
        L1.setText(M_name.getText());
        L2.setText("About movie");
        About.append(mabout);
        System.out.print(mabout+"1");
        namehall.setVisible(false);
}//GEN-LAST:event_M_MovieInfoMouseReleased

    private void M_t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_t1ActionPerformed
        String time=M_t1.getText();
        String movieName=M_name.getText();
        String hall=M_hall1.getText();
        int k=1;
        String S_No="";
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abcd","root","sps");
            Statement stmt=con.createStatement();
            String query= "Select * from movie_detail;" ;
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()) {
                String movie_Name=rs.getString(2);
                if(movie_Name.equalsIgnoreCase(M_name.getText())){
                    S_No=rs.getString(1);
                }
            }


            M_perso mp=new M_perso();
/*M_Book mb=new M_Book();
mb.setVisible(true);*/
            mp.choice1(k,S_No,hall,movieName,time);

            mp.setVisible(true);
            mp.setAlwaysOnTop(true);
            this.dispose();

        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
}//GEN-LAST:event_M_t1ActionPerformed

    private void M_t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_t7ActionPerformed
        String time=M_t7.getText();
        String movieName=M_name.getText();
        String hall=M_hall3.getText();
        int k=7;
        String S_No="";
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abcd","root","sps");
            Statement stmt=con.createStatement();
            String query= "Select * from movie_detail;" ;
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()) {
                String movie_Name=rs.getString(2);
                if(movie_Name.equalsIgnoreCase(M_name.getText())) {
                    S_No=rs.getString(1);
                }
            }
            M_perso mp=new M_perso();
            mp.choice1(k,S_No,hall,movieName,time);
            mp.setVisible(true);
            this.dispose();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
}//GEN-LAST:event_M_t7ActionPerformed

    private void M_t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_t4ActionPerformed
        String time=M_t4.getText();
        String movieName=M_name.getText();
        String hall=M_hall2.getText();
        int k=4;
        String S_No="";
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abcd","root","sps");
            Statement stmt=con.createStatement();
            String query= "Select * from movie_detail;" ;
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()) {
                String movie_Name=rs.getString(2);
                if(movie_Name.equalsIgnoreCase(M_name.getText())){
                    S_No=rs.getString(1);
                }
            }
            M_perso mp=new M_perso();
            mp.choice1(k,S_No,hall,movieName,time);
            mp.setVisible(true);
            this.dispose();

        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_M_t4ActionPerformed

    private void M_t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_t5ActionPerformed
        String time=M_t5.getText();
        String movieName=M_name.getText();
        String hall=M_hall2.getText();
        int k=5;
        String S_No="";
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abcd","root","sps");
            Statement stmt=con.createStatement();
            String query= "Select * from movie_detail;" ;
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()) {
                String movie_Name=rs.getString(2);
                if(movie_Name.equalsIgnoreCase(M_name.getText())){
                    S_No=rs.getString(1);
                }
            }
            M_perso mp=new M_perso();
            mp.choice1(k,S_No,hall,movieName,time);
            mp.setVisible(true);
            this.dispose();

        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
}//GEN-LAST:event_M_t5ActionPerformed

    private void M_t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_t8ActionPerformed
        String time=M_t8.getText();
        String movieName=M_name.getText();
        String hall=M_hall3.getText();
        int k=8;
        String S_No="";
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abcd","root","sps");
            Statement stmt=con.createStatement();
            String query= "Select * from movie_detail;" ;
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()) {
                String movie_Name=rs.getString(2);
                if(movie_Name.equalsIgnoreCase(M_name.getText())){
                    S_No=rs.getString(1);
                }
            }
            M_perso mp=new M_perso();
            mp.choice1(k,S_No,hall,movieName,time);
            mp.setVisible(true);
            this.dispose();

        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
}//GEN-LAST:event_M_t8ActionPerformed

    private void M_t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_t2ActionPerformed
        String time=M_t2.getText();
        String movieName=M_name.getText();
        String hall=M_hall1.getText();

        int k=2;
        String S_No="";
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abcd","root","sps");
            Statement stmt=con.createStatement();
            String query= "Select * from movie_detail;" ;
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()) {
                String movie_Name=rs.getString(2);
                if(movie_Name.equalsIgnoreCase(M_name.getText())){
                    S_No=rs.getString(1);
                }
            }
            M_perso mp=new M_perso();
            mp.choice1(k,S_No,hall,movieName,time);
            mp.setVisible(true);
            this.dispose();

        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
}//GEN-LAST:event_M_t2ActionPerformed

    private void M_hall3InfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_hall3InfoMouseReleased
        int aaaa=3;
        M_HInfo mhi = new M_HInfo();
        mhi.setVisible(true);
        mhi.hinfo(aaaa);
        this.dispose();
}//GEN-LAST:event_M_hall3InfoMouseReleased

    private void M_t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_t3ActionPerformed
        String time=M_t3.getText();
        String movieName=M_name.getText();
        String hall=M_hall1.getText();
        int k=3;
        String S_No="";
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abcd","root","sps");
            Statement stmt=con.createStatement();
            String query= "Select * from movie_detail;" ;
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()) {
                String movie_Name=rs.getString(2);
                if(movie_Name.equalsIgnoreCase(M_name.getText())){
                    S_No=rs.getString(1);
                }
            }
            M_perso mp=new M_perso();
            mp.choice1(k,S_No,hall,movieName,time);
            mp.setVisible(true);
            this.dispose();

        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_M_t3ActionPerformed

    private void M_t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_t6ActionPerformed
        String time=M_t6.getText();
        String movieName=M_name.getText();
        String hall=M_hall2.getText();
        int k=6;
        String S_No="";
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abcd","root","sps");
            Statement stmt=con.createStatement();
            String query= "Select * from movie_detail;" ;
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()) {
                String movie_Name=rs.getString(2);
                if(movie_Name.equalsIgnoreCase(M_name.getText())){
                    S_No=rs.getString(1);
                }
            }
            M_perso mp=new M_perso();
            mp.choice1(k,S_No,hall,movieName,time);
            mp.setVisible(true);
            this.dispose();

        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
}//GEN-LAST:event_M_t6ActionPerformed

    private void M_t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_t9ActionPerformed
        String time=M_t9.getText();
        String movieName=M_name.getText();
        String hall=M_hall3.getText();
        int k=9;
        String S_No="";
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abcd","root","sps");
            Statement stmt=con.createStatement();
            String query= "Select * from movie_detail;" ;
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()) {
                String movie_Name=rs.getString(2);
                if(movie_Name.equalsIgnoreCase(M_name.getText())){
                    S_No=rs.getString(1);
                }
            }
            M_perso mp=new M_perso();
            mp.choice1(k,S_No,hall,movieName,time);
            mp.setVisible(true);
            this.dispose();

        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }        // TODO add your handling code here:
}//GEN-LAST:event_M_t9ActionPerformed

    private void M_hall1InfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_hall1InfoMouseReleased
        int aaaa=1;
        M_HInfo mhi = new M_HInfo();
        mhi.setVisible(true);
        mhi.hinfo(aaaa);
        this.dispose();
}//GEN-LAST:event_M_hall1InfoMouseReleased

    private void M_hall2InfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_hall2InfoMouseReleased
        int aaaa=2;
        M_HInfo mhi = new M_HInfo();
        mhi.setVisible(true);
        mhi.hinfo(aaaa);
        this.dispose();
}//GEN-LAST:event_M_hall2InfoMouseReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new M_Time().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea About;
    private javax.swing.JLabel About1;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel M_DP;
    private javax.swing.JLabel M_DP1;
    private javax.swing.JLabel M_DP2;
    private javax.swing.JLabel M_DP3;
    private javax.swing.JLabel M_MovieInfo;
    private javax.swing.JLabel M_category;
    private javax.swing.JLabel M_hall1;
    private javax.swing.JLabel M_hall1Info;
    private javax.swing.JLabel M_hall2;
    private javax.swing.JLabel M_hall2Info;
    private javax.swing.JLabel M_hall3;
    private javax.swing.JLabel M_hall3Info;
    private javax.swing.JLabel M_hrs;
    private javax.swing.JLabel M_lang;
    private javax.swing.JLabel M_name;
    private javax.swing.JLabel M_rating;
    private javax.swing.JButton M_t1;
    private javax.swing.JButton M_t2;
    private javax.swing.JButton M_t3;
    private javax.swing.JButton M_t4;
    private javax.swing.JButton M_t5;
    private javax.swing.JButton M_t6;
    private javax.swing.JButton M_t7;
    private javax.swing.JButton M_t8;
    private javax.swing.JButton M_t9;
    private javax.swing.JLabel M_votes1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JDialog jl1;
    private javax.swing.JLabel namehall;
    // End of variables declaration//GEN-END:variables

}
